### ISSUE TITLE
Please update description to avoid misleading users to believe this is an official project

### ISSUE THREAD

**Issue by Ovilia** [leisureSkyblue/echarts-provinces-map#1]
Hi. Thanks for making this repo to helper developers but as a PMC member of Apache ECharts, I would request some changes in this repo's description both in Readme.md and project's about.

According to Apache Software Foundation branding policy, a third-party repo should not mislead others to believe this is an official project.

So please edit the description like:

> This project is developed by the hobbyist community and is not an official work of Apache ECharts. This project provides the map data of each province used to map China with Apache ECharts. This project contains the latest administrative plan...

Please also notice that if you are maintaining this repo, you are responsible to make sure that the map data is correct and follows the rules of local governments.

嗨，感谢开发本项目帮助开发者。但是作为 Apache ECharts PMC 成员，我需要提醒您修改本项目的描述，包括 Readme.md 和项目的 About。

根据 Apache 软件基金会的品牌政策，第三方项目不能让他人误认为这是官方项目。

所以，请将项目描述修改为类似：

> 本项目由社区爱好者开发，非 Apache ECharts 官方作品。本项目提供绘制中国地图所使用的各省份地图数据，以实现在 Apache ECharts 中绘制地图。本项目包含最新的行政规划……

另外友情提示一下，如果您是本项目的维护者，您有义务确保地图数据的正确性，以及符合相关的政策规定。

**Comment by leisureSkyblue** [comment]
感谢您的善意提醒，我已按您的建议进行了相应修改。
